### ISSUE TITLE
Auslagern von API calls in entsprechendes TCA

### ISSUE THREAD

**Issue by o-ba** [plobacher/extbasebookexamplev8#1]
Hallo,

mir fiel auf, dass $GLOBALS['TCA'] Konfiguration noch in der ext_tables.php geschrieben wird. Diese sollten in die entsprechenden TCA's verschoben werden.
Siehe auch: https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.5/Breaking-78384-FrontendIgnoresTCAInExtTables.html

Grüße,
Oliver

**Comment by schams-net** [comment]
Hi Oliver. Thanks for your feedback. I made a note to take this into account for the next version/edition of the TYPO3 Extbase Book.

**Comment by schams-net** [comment]
3rd edition of the **TYPO3 Extbase Book** follows the new convention and provides detailed explanation. This also includes the example extension, which will be published under <https://github.com/typo3-extbase-book>.
